{
  "name": "kenguru-yandex-reviews-network-v3",
  "version": "3.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.21.2",
    "playwright": "1.51.1"
  }
}
